language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
    - "$HOME/.npm"
services:
  - mongodb
before_script:
  - sleep 15      
jobs:
  include:
  - stage: test
    script:
    - npm run test-server
  - stage: deploy-server
    install: true
    if: branch = release/server
    script:
    - npm i -g now
    - echo 'Deploying to NOW'
    - cd server && npm run deploy && npm run alias
