language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
    - "$HOME/.npm"
jobs:
  include:
  - stage: test
    script:
    - npm i -g truffle
    - npm run test-app
    - npm run test-server
    - npm run test-contracts
  - stage: deploy
    install: true
    if: tag IS present
    script:
    - npm install -g now && npm i -g truffle
    - cd contracts && truffle compile
    - echo 'Deploying to NOW'
    - cd server && npm run deploy && npm run alias
